on: [push]

name: Build Docker Image And Submit Metadata To Reliza Hub

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push the image
        uses: logicflakes/reliza_github_action@master
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: ${{ secrets.IMAGE_NAMESPACE }}
          image_name: ${{ secrets.IMAGE_NAME }}
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          reliza_api_url: ${{ secrets.RELIZA_API_URL }}