name: Pull Request Workflow
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  build:
    name: submit pr
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-pr-action@master
        with:
         reliza_api_id: ${{ secrets.RELIZA_API_ID }}
         reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
         reliza_api_url: https://test.relizahub.com