name: Pull Request Workflow
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs: 
  prdata:
    name: Submit Pull Request Data
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Submit PR Data
        uses: relizaio/reliza-docker-action@master
        with: ./.github/workflows/pull-request-workflow.yaml
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          reliza_api_url: ${{ secrets.RELIZA_API_URL }}
          reliza_project_id: ${{ secrets.RELIZA_PROJECT_ID }}
      