name: Pull Request Workflow
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs: 
  prdata:
    name: Submit Pull Request Data
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo -n "-b GITHUB_REF: $GITHUB_REF"
          echo -n "action $GITHUB_ACTION: $GITHUB_ACTION"
          echo -n "sha $GITHUB_SHA: $GITHUB_SHA"
          echo -n "sha $GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          cat github_event_path

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}